apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: services
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 22
    targetPort: 22
    name: ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
