apiVersion: v1
kind: Service
metadata:
  name: pma-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: services
spec:
  selector:
    app: pma
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
  - port: 5000
    targetPort: 5000
    name: pma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: pma-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000