apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: services
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
  - port: 5050
    targetPort: 5050
    name: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-volume-claim
        